version: "3.9"
services:
  db:
    container_name: db
    image : mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  cache:
    container_name: cache
    image : redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - .data:/data

  app:
    container_name: app
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      ENV: CONTAINER
      MONGODB_URI: mongodb://db:27017
      REDIS_HOST: cache
    depends_on:
      - db
      - cache
    links:
      - db
      - cache

volumes:
  db: {}