version: "3.9"
services:
  db:
    container_name: db
    image : mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  app:
    container_name: app
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      ENV: CONTAINER
      MONGODB_URI: mongodb://db:27017
    depends_on:
      - db
    links:
      - db

volumes:
  db: {}